# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Remember' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RealmSwift', '4.4.0'

  # Pods for Remember

  target 'RememberTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RememberUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharePreview' do
    inherit! :search_paths

    # Pods for SharePreview
    pod 'SwiftSoup', '2.3.1'
    pod 'RealmSwift', '4.4.0'
  end
  
  target 'ios_dependencies' do
    inherit! :search_paths

    # Pods for SharePreview
    pod 'SwiftSoup', '2.3.1'
    pod 'RealmSwift', '4.4.0'
  end
end


