# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Remember
  pod 'SDWebImageSwiftUI', '1.3.3'

  target 'ios_app_tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_app_uitests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_feature_preview' do
    inherit! :search_paths

    # dependencies
    pod 'SwiftSoup', '2.3.1'
  end
  
  target 'ios_feature_hub' do
    inherit! :search_paths
    
    # dependencies
  end
  
  target 'ios_dependencies' do
    inherit! :search_paths

    # dependencies
    pod 'SwiftSoup', '2.3.1'
    pod 'RealmSwift', '4.4.0'
  end
end


