# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Remember' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Remember

  target 'RememberTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RememberUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharePreview' do
    inherit! :search_paths

    # Pods for SharePreview
    pod 'SwiftSoup'
  end
end


